### ISSUE TITLE
Indefinite switching between apps in different spaces

### ISSUE THREAD

**Issue by LiamGoodacre** [puffnfresh/iridium#10]
Effect: Indefinite switching between the two spaces/apps
I've found each of these methods seem to stop it:
- Switch to an app that isn't confined to any particular space (always seems to work)
- Keep trying to switch to one of the two apps (need to time it right)
- Switch layouts a few times (seems to stop when switching to full screen layout)

To replicate the switching:
- Space 1: Firefox
- Space 2: Sublime Text
- Focus Firefox
- Cmd+Tab to switch to Sublime Text

**Comment by puffnfresh** [comment]
This is an excellent bug report, thank you!
