### ISSUE TITLE
Somehow keyboard layout is not respected

### ISSUE THREAD

**Issue by LiamGoodacre** [puffnfresh/iridium#9]
I am currently using Dvorak.
To use the keyboard shortcuts involving `J` & `K` I have to instead use `H` & `T`.

Testing `master` as of commit 2dc438475962b62f6ca8d00f0dff3add87418dec
System: OS X 10.9.3
Both user and system keyboard layouts have been defaulted to Dvorak.

**Comment by puffnfresh** [comment]
Yeah, iridium uses the built-in key codes of the keyboard. It's definitely a bug and we should use the char codes.

**Comment by Melvar** [comment]
Char codes would preclude using keys that do not produce characters. Keysyms are what this sort of thing should work with.
